#! vim: set ft=yaml ts=2:
---

sudo: required

env:
  - distribution: debian
    version: stretch

services:
  - docker

before_install:
  - container_id=$(mktemp)
  - sudo docker pull ${distribution}:${version}
  - sudo docker run -d ${distribution}:${version} /bin/sh -c "/bin/bash" > ${container_id}
  - echo ${container_id}
  - cat ${container_id}
  - sudo docker exec "$(cat ${container_id})" "uname -a"
