#! vim: set ft=yaml ts=2:
---

sudo: required
language: minimal
services:
  - docker

env:
  - distribution: debian
    version: stretch

before_install:
  - container_id=$(mktemp)
  - sudo docker pull ${distribution}:${version}
  - sudo docker run -d ${distribution}:${version} /bin/sh -c "sleep inf" > ${container_id}
  - echo ${container_id}
  - cat ${container_id}
  - sudo docker ps
  - sudo docker exec "$(cat ${container_id})" "/bin/uname -a"
