#! vim: set ft=yaml ts=2:
---

- debug: var=i18n.locales
  tags:
    - never
    - debug

- block:
  - name: packages does exist
    package:
      name: locales
      state: present
  - name: Ensure a locale exists {{ item }}
    with_items: "{{ i18n.locales }}"
    locale_gen:
      name: "{{ item }}"
      state: present
  when: ansible_distribution + ansible_distribution_major_version in i18n.platforms
