FROM debian:stretch

RUN apt-get update -y && apt-get install -y --no-install-recommends \
    build-essential \
    libffi-dev \
    libssl-dev \
    python-dev \
    python-pip \
    python-setuptools \
    git \
    systemd \
 && rm -rf /var/lib/apt/lists/*

RUN pip install wheel && pip install ansible && pip install ansible-lint

RUN mkdir -p /etc/ansible && echo "[local]\nlocalhost ansible_connection=local" > /etc/ansible/hosts

ENTRYPOINT ["/bin/systemd"]
