FROM ubuntu:xenial

RUN apt-get update -y && apt-get install -y --no-install-recommends \
    build-essential \
    libffi-dev \
    libssl-dev \
    python-dev \
    python-pip \
    python-setuptools \
    git \
    systemd \
 && rm -rf /var/lib/apt/lists/*

RUN pip install wheel && pip install ansible && pip install ansible-lint

ENTRYPOINT ["/sbin/init"]
